# Change these first
owner: mohhasbias # Your GitHub organization or username, where this repository lives
repo: cw-conn-status-page # The name of this repository

sites:
  - name: Chatwoot
    url: https://dev-cw.hsi.id
  - name: Notifikasi API
    url: https://notifikasi.hsi.id/ping
  - name: DBS API
    url: https://dbs.hsi.id/useruser/regcode/12345
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /cw-conn-status-page
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Chatwoot Connector
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: "**Chatwoot Connector**"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: "System Status"
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
